(in-package #:nerimux/test/model)

;;;; layout tests — part B: layout-find-parent / layout-find-leaf NIL-node arm
;;;; coverage.  The named-layout system (%layout-even-h/v, %layout-main,
;;;; %layout-tiled, %build-grid-tree, apply-named-layout) was removed along
;;;; with its tests; layout-find-leaf-nil-node-arm-returns-nil survives here
;;;; because it exercises the unrelated define-layout-fold NIL arm.
(describe "layout-tree-suite"

  ;; layout-find-leaf on a NIL node returns NIL — exercises the NIL etypecase arm
  ;; of the define-layout-fold generated function for a non-extent traversal.
  (it "layout-find-leaf-nil-node-arm-returns-nil"
    ;; layout-find-leaf is generated by define-layout-fold and has a (null nil) arm.
    ;; Exercising it here confirms the null branch is reachable for fold functions.
    (let ((p (tl-pane 1 10 5)))
      (expect (null (layout-find-leaf nil p))))))
