(require :asdf)

(setf asdf/source-registry:*source-registry*
      (make-hash-table :test (function equal)))

(load (truename "nerimux.asd"))
(dolist (spec '((:asdf/action "COMPONENT-DEPENDS-ON")
                (:asdf/action "MAP-DIRECT-DEPENDENCIES")
                (:asdf/action "REDUCE-DIRECT-DEPENDENCIES")
                (:asdf/action "ACTION-VALID-P")
                (:asdf/action "INPUT-FILES")
                (:asdf/action "OUTPUT-FILES")
                (:asdf/action "OPERATION-DONE-P")
                (:asdf/action "COMPONENT-OPERATION-TIME")
                (:asdf/operation "FIND-OPERATION")
                (:asdf/find-component "RESOLVE-DEPENDENCY-SPEC")
                (:asdf/session "GET-FILE-STAMP")
                (:asdf/find-system "LOCATE-SYSTEM")
                (:asdf/find-system "DEFINITION-DEPENDENCIES-UP-TO-DATE-P")
                (:asdf/action "COMPUTE-ACTION-STAMP")))
  (let ((symbol (find-symbol (second spec) (first spec))))
    (when (and symbol (fboundp symbol))
      (eval `(trace ,symbol)))))
(format t "STAMP=~S~%" (asdf/session:get-file-stamp (truename "nerimux.asd")))
(finish-output)
(format t "BEFORE-FIND~%")
(finish-output)
(sb-thread:make-thread
 (lambda ()
   (sleep 5)
   (sb-thread:interrupt-thread
    (sb-thread:main-thread)
    (lambda ()
      (format *error-output* "WATCHDOG~%")
      (sb-debug:backtrace 100)
      (finish-output *error-output*)
      (sb-ext:exit :code 2)))))
(format t "SYSTEM=~S~%" (asdf:find-system "nerimux"))
(format t "AFTER-FIND~%")
(finish-output)
