(require :asdf)
(setf asdf/source-registry:*source-registry*
      (make-hash-table :test (function equal)))
(load (truename "system/asdf-test-components.lisp"))
(format t "AFTER-DATA~%")
(finish-output)
(load (truename "asdf-metadata-module-probe.asd"))
(format t "AFTER-ASD~%")
(finish-output)
(format t "BEFORE-DUMMY~%")
(finish-output)
(let ((dummy (make-instance 'asdf/system:system :name "dummy")))
  (format t "AFTER-DUMMY=~S~%" dummy)
  (finish-output))
