(require :asdf)

(setf asdf/source-registry:*source-registry*
      (make-hash-table :test (function equal)))

(format t "BEFORE-DIRECT-LOAD~%")
(finish-output)
(load (truename "nerimux.asd"))
(format t "AFTER-DIRECT-LOAD~%")
(finish-output)
(format t "BEFORE-DUMMY-1~%")
(finish-output)
(let ((dummy (make-instance 'asdf/system:system :name "dummy-1")))
  (format t "AFTER-DUMMY-1~%")
  (finish-output))
(format t "BEFORE-PROBE~%")
(finish-output)
(asdf:defsystem "nerimux/post-load-probe" :components nil)
(format t "AFTER-PROBE~%")
(finish-output)
(format t "BEFORE-DUMMY-2~%")
(finish-output)
(let ((dummy (make-instance 'asdf/system:system :name "dummy-2")))
  (format t "AFTER-DUMMY-2~%")
  (finish-output))
