(require :asdf)

(setf asdf/source-registry:*source-registry*
      (make-hash-table :test (function equal)))

(defparameter *end* (gensym "END"))

(with-open-file (stream (truename "nerimux.asd"))
  (let ((*package* (find-package :asdf-user))
        (forms nil))
    (loop repeat 3
          do (push (read stream nil *end*) forms))
    (setf forms (nreverse forms))
    (eval (first forms))
    (let ((*load-truename* (truename "nerimux.asd"))
          (*load-pathname* (truename "nerimux.asd")))
      (eval (second forms)))
    (let* ((main (if (string= (or (uiop:getenv "PROBE_COPY") "yes") "no")
                     (third forms)
                     (copy-tree (third forms))))
           (options (cddr main))
           (mode (or (uiop:getenv "PROBE_MODE") "full")))
      (cond
        ((string= mode "no-components")
         (setf (getf options :components) nil))
        ((string= mode "no-in-order-to")
         (setf (getf options :in-order-to) nil))
        ((string= mode "no-depends-on")
         (setf (getf options :depends-on) nil))
        ((string= mode "no-build")
         (setf (getf options :build-operation) nil
               (getf options :build-pathname) nil
               (getf options :entry-point) nil))
        ((string= mode "no-components-in-order")
         (setf (getf options :components) nil
               (getf options :in-order-to) nil))
        ((string= mode "component-prefix")
         (let* ((components (getf options :components))
                (prefix (parse-integer (or (uiop:getenv "PROBE_PREFIX") "0"))))
           (setf (getf options :components)
                 (subseq components 0 (min prefix (length components))))))
        ((string= mode "src-prefix")
         (let* ((src (first (getf options :components)))
                (src-options (cddr src))
                (components (getf src-options :components))
                (prefix (parse-integer (or (uiop:getenv "PROBE_PREFIX") "0"))))
           (setf (getf src-options :components)
                 (subseq components 0 (min prefix (length components))))
           (format t "SRC-CHILDREN=~D SRC-FORM=~S~%"
                   (length (getf src-options :components))
                   src)))
        ((string= mode "first-empty")
         (let* ((src (first (getf options :components)))
                (first-child (first (getf (cddr src) :components)))
                (first-options (cddr first-child)))
           (setf (getf first-options :components) nil)
           (format t "FIRST-FORM=~S~%" first-child)))
        ((string= mode "first-file")
         (let* ((src (first (getf options :components)))
                (first-child (first (getf (cddr src) :components)))
                (first-options (cddr first-child)))
           (setf (getf first-options :components) '((:file "package")))
           (format t "FIRST-FORM=~S~%" first-child)))
        ((string= mode "src-copy-empty")
         (let* ((src (copy-tree (first (getf options :components))))
                (src-options (cddr src)))
           (setf (getf src-options :components) nil)
           (setf (getf options :components) (list src))
           (format t "SRC-FORM=~S~%" src)))
        ((string= mode "src-fresh")
         (setf (getf options :components)
               '((:module "src" :serial t :components nil))))
        ((string= mode "fresh-components")
         (setf (getf options :components)
               '((:module "src" :serial t :components nil))))
      )
      (let ((strip (uiop:getenv "PROBE_STRIP")))
        (when strip
          (setf (getf options
                      (intern (string-upcase strip) (find-package :keyword)))
                nil)
          (format t "STRIPPED=~A~%" strip)))
      (format t "BEFORE-MAIN MODE=~A~%" mode)
      (finish-output)
      (let ((*load-truename* (truename "nerimux.asd"))
            (*load-pathname* (truename "nerimux.asd")))
        (eval main))
      (format t "AFTER-MAIN~%")
      (finish-output)
      (let ((system (asdf/system-registry:registered-system "nerimux")))
        (format t "REGISTERED-CHILDREN=~D~%"
                (length (asdf:component-children system)))
        (dolist (child (asdf:component-children system))
          (format t "CHILD=~S TYPE=~S CHILDREN=~D~%"
                  (asdf:component-name child)
                  (type-of child)
                  (length (asdf:component-children child)))))
      (finish-output)
      (format t "BEFORE-DUMMY-1~%")
      (finish-output)
      (let ((dummy (make-instance 'asdf/system:system :name "dummy-1")))
        (format t "AFTER-DUMMY-1-CREATE~%")
        (finish-output)
        (format t "DUMMY-1=~S~%" dummy))
      (format t "AFTER-DUMMY-1~%")
      (finish-output)
      (format t "BEFORE-PROBE~%")
      (finish-output)
      (let ((*load-truename* (truename "nerimux.asd"))
            (*load-pathname* (truename "nerimux.asd")))
        (asdf:defsystem "nerimux/option-probe" :components nil))
      (format t "AFTER-PROBE~%")
      (finish-output)
      (format t "BEFORE-DUMMY-2~%")
      (finish-output)
      (let ((dummy (make-instance 'asdf/system:system :name "dummy-2")))
        (format t "AFTER-DUMMY-2-CREATE~%")
        (finish-output)
        (format t "DUMMY-2=~S~%" dummy))
      (format t "AFTER-DUMMY-2~%")
      (finish-output))))
