(in-package #:nerimux/pty)

(defvar *pty-processes* (make-hash-table :synchronized t))
(defun %string-non-empty-p (value) (and (stringp value) (plusp (length value))))
(defun %spawn-directory (start-dir)
  (when (%string-non-empty-p start-dir)
    (handler-case (truename start-dir) (file-error () nil))))
(defun %default-shell ()
  (let ((shell (sb-ext:posix-getenv "SHELL")))
    (if (%string-non-empty-p shell) shell "/bin/sh")))
(defun %target-program-and-args (default-command)
  (if (%string-non-empty-p default-command)
      (values "/bin/sh" (list "-c" default-command) nil)
      (let ((shell (%default-shell)))
        (values shell nil (not (char= (char shell 0) #\/))))))
(defun %remember-pty-process (master-fd pty)
  (setf (gethash master-fd *pty-processes*) pty))
(defun %take-pty-process (master-fd)
  (let ((pty (gethash master-fd *pty-processes*)))
    (remhash master-fd *pty-processes*) pty))
(defparameter +pty-child-wait-timeout+ (cl-date-kit:duration-of-seconds 5))
(defconstant +pty-write-timeout-seconds+ 2)
(defun pty-child-exit-status (master-fd &optional (timeout +pty-child-wait-timeout+))
  (let* ((pty (gethash master-fd *pty-processes*))
         (process (and pty (cl-tty-kit:pty-process pty))))
    (when process
      (handler-case
          (progn
            (cl-concurrent-kit:with-timeout timeout (sb-ext:process-wait process))
            (let ((code (sb-ext:process-exit-code process)))
              (when code
                (if (eq (sb-ext:process-status process) :signaled)
                    (values nil :signaled) (values code :exited)))))
        (cl-concurrent-kit:operation-timed-out () nil) (error () nil)))))
(defun forkpty-with-shell (rows cols &key start-dir default-command environment)
  (declare (type fixnum rows cols))
  (multiple-value-bind (program args search-p) (%target-program-and-args default-command)
    (declare (ignore search-p))
    (let ((pty (cl-tty-kit:make-pty :program program :args args :environment environment
                                    :directory (%spawn-directory start-dir)))
          (success nil))
      (unwind-protect
           (let ((master (cl-tty-kit:pty-fd pty)) (pid (cl-tty-kit:pty-pid pty)))
             (set-pty-size master rows cols) (%remember-pty-process master pty)
             (setf success t) (values master pid ""))
        (unless success
          (handler-case (cl-tty-kit:close-pty pty)
            (cl-tty-kit:pty-operation-failed () nil)))))))
(defun pty-close (master-fd child-pid)
  (when (plusp child-pid)
    (handler-case (sb-posix:kill child-pid sb-posix:sighup)
      (sb-posix:syscall-error () nil)))
  (when (>= master-fd 0)
    (let ((pty (%take-pty-process master-fd)))
      (if pty
          (handler-case (sb-ext:process-close (cl-tty-kit:pty-process pty))
            (stream-error () nil) (file-error () nil))
          (handler-case (sb-posix:close master-fd)
            (sb-posix:syscall-error () nil))))))
