(in-package #:nerimux/pty)
(defconstant +max-sane-rows+ 1000)
(defconstant +max-sane-cols+ 1000)
(defconstant +default-term-rows+ 24)
(defconstant +default-term-cols+ 80)
(defun terminal-size ()
  (multiple-value-bind (cols rows) (cl-tty-kit:terminal-size +stdout-fd+)
    (if (and (integerp rows) (integerp cols) (<= 1 rows +max-sane-rows+)
             (<= 1 cols +max-sane-cols+))
        (values rows cols)
        (values +default-term-rows+ +default-term-cols+))))
