(in-package #:nerimux/terminal/csi)

(define-csi-rule-set csi-extended-rules
                     ((and (null private) (eql intermed #\$) (char= final #\z))
                      (let ((p3 (%csi-leading-int (third params)))
                            (p4 (%csi-leading-int (fourth params))))
                        (decera screen p1 p2 p3 p4)))
                     ((and (null private) (eql intermed #\$) (char= final #\x))
                      (let ((p3 (%csi-leading-int (third params)))
                            (p4 (%csi-leading-int (fourth params)))
                            (p5 (%csi-leading-int (fifth params))))
                        (decfra screen p1 p2 p3 p4 p5)))
                     ((and (null private) (eql intermed #\$) (char= final #\v))
                      (let ((p3 (%csi-leading-int (third params)))
                            (p4 (%csi-leading-int (fourth params)))
                            (p6 (%csi-leading-int (sixth params)))
                            (p7 (%csi-leading-int (seventh params))))
                        (deccra screen p1 p2 p3 p4 p6 p7)))
                     ((and (null private) (null intermed) (char= final #\h))
                      (set-ansi-mode screen params))
                     ((and (null private) (null intermed) (char= final #\l))
                      (reset-ansi-mode screen params))
                     ((and (eql intermed #\!) (char= final #\p))
                      (decstr-action screen))
                     ((and (null private) (char= final #\t))
                      (enqueue-xtwinops-reply screen p1))
                     ((and (eql intermed #\Space) (char= final #\q))
                      (set-cursor-shape screen p1)))
