(in-package #:nerimux/terminal/csi)

;;;; CSI device queries, reports, tabulation, and private modes.
(define-csi-rule-set csi-device-rules
                     ((and (null intermed) (char= final #\n) (= p1 5))
                      (enqueue-dsr-reply screen))
                     ((and (null intermed) (char= final #\n) (= p1 6))
                      (enqueue-cpr-reply screen))
                     ((and (null intermed) (char= final #\r))
                      (multiple-value-call #'decstbm
                        screen
                        (%csi-decstbm-params screen p1 p2)))
                     ((and (null intermed) (char= final #\I))
                      (cursor-cht screen p1*))
                     ((and (null intermed) (char= final #\Z))
                      (cursor-cbt screen p1*))
                     ((and (null intermed) (char= final #\g))
                      (clear-tab-stops screen p1))
                     ((and (null intermed) (null private) (char= final #\c))
                      (enqueue-da1-reply screen))
                     ((and (eql private #\>) (char= final #\c))
                      (enqueue-da2-reply screen))
                     ((and (eql private #\>) (char= final #\t))
                      (push-title-stack screen))
                     ((and (eql private #\<) (char= final #\t))
                      (pop-title-stack screen))
                     ((and (eql private #\>) (char= final #\q))
                      (enqueue-xtversion-reply screen))
                     ((and (eql private #\=) (char= final #\c))
                      (enqueue-da3-reply screen))
                     ((and (eql private #\?) (char= final #\h))
                      (dec-pm-set screen params))
                     ((and (eql private #\?) (char= final #\l))
                      (dec-pm-reset screen params))
                     ((and (eql private #\?)
                           (eql intermed #\$)
                           (char= final #\p)) (enqueue-decrqm-reply screen p1))
                     ((and (null private) (eql intermed #\$) (char= final #\p))
                      (enqueue-decrqm-ansi-reply screen p1)))
