(defpackage #:nerimux/terminal/types
  (:use #:cl)
  (:import-from #:cl-concurrent-kit #:make-lock)
  (:documentation
   "DOMAIN layer, the DATA half of the terminal emulator.  Defines the two structs
    the whole emulator is written against — CELL (character, colours, attribute
    bits, width) and SCREEN (the grid, the cursor, the SGR pen, scrollback, and the
    dozens of DEC/ANSI mode flags) — together with their attribute-bit constants and
    pure grid access.  Owns no behaviour beyond allocation and slot access; every
    mutation lives in nerimux/terminal/actions.")
  (:export
   #:+attr-bold+
   #:+attr-dim+
   #:+attr-reverse+
   #:+attr-underline+
   #:+attr-blink+
   #:+attr-italic+
   #:+attr-conceal+
   #:+attr-strikethrough+
   #:+attr2-double-underline+
   #:+attr2-overline+
   #:+true-color-flag+
   #:+default-color+
   #:+unicode-replacement-char+
   #:+title-stack-max-depth+
   #:+default-screen-width+
   #:+default-screen-height+
   #:%make-blank-cells
   #:cell
   #:make-cell
   #:cell-p
   #:cell-char
   #:cell-fg
   #:cell-bg
   #:cell-attrs
   #:cell-attrs2
   #:cell-ul-color
   #:cell-combining
   #:cell-width
   #:cell-hyperlink
   #:blank-cell
   #:clamp
   #:safe-code-char
   #:+surrogate-first+
   #:+surrogate-last+
   #:surrogate-code-point-p
   #:char-width
   #:screen
   #:%make-screen
   #:make-screen
   #:screen-p
   #:screen-width
   #:screen-height
   #:screen-cells
   #:screen-cursor-x
   #:screen-cursor-y
   #:screen-cur-fg
   #:screen-cur-bg
   #:screen-cur-attrs
   #:screen-cur-attrs2
   #:screen-cur-ul-color
   #:screen-scroll-top
   #:screen-scroll-bottom
   #:screen-parser
   #:screen-dirty-p
   #:screen-lock
   #:screen-alt-cells
   #:screen-alt-cursor-x
   #:screen-alt-cursor-y
   #:screen-saved-cursor
   #:screen-cursor-visible
   #:screen-copy-mode-p
   #:screen-copy-hide-position
   #:screen-copy-offset
   #:screen-scrollback
   #:screen-scrollback-wrapped
   #:screen-prompt-marks
   #:screen-history-trimmed
   #:screen-line-sizes
   #:screen-copy-mark
   #:screen-copy-mark-offset
   #:screen-copy-cursor
   #:screen-copy-selecting
   #:screen-copy-exit-on-bottom
   #:screen-copy-mode-entered-by-mouse-p
   #:screen-last-char
   #:screen-cursor-shape
   #:screen-bell-pending
   #:screen-copy-search-term
   #:screen-copy-search-index
   #:screen-copy-search-total
   #:screen-copy-search-direction
   #:screen-copy-line-selection-p
   #:screen-copy-rect-select-p
   #:screen-insert-mode
   #:screen-newline-mode
   #:screen-reverse-screen
   #:screen-bracketed-paste
   #:screen-app-cursor-keys
   #:screen-title
   #:screen-title-stack
   #:screen-cwd
   #:screen-autowrap
   #:screen-pending-wrap
   #:screen-origin-mode
   #:screen-focus-events
   #:screen-charset
   #:screen-g0-charset
   #:screen-g1-charset
   #:screen-g2-charset
   #:screen-g3-charset
   #:screen-active-g
   #:screen-single-shift
   #:screen-tab-stops
   #:screen-response-queue
   #:screen-passthrough-queue
   #:screen-clipboard-queue
   #:+osc-default-fg+
   #:+osc-default-bg+
   #:screen-osc-default-fg
   #:screen-osc-default-bg
   #:screen-current-hyperlink
   #:screen-palette-overrides
   #:%palette-override-get
   #:%palette-override-set
   #:%palette-override-clear
   #:%palette-override-clear-all
   #:screen-wrapped-rows
   #:%mark-line-wrapped
   #:%line-wrapped-p
   #:%clear-line-wrapped
   #:%clear-all-line-wrapped
   #:%shift-line-wrapped-up
   #:screen-cell
   #:screen-clear-dirty
   #:screen-resize
   #:screen-consume-bell
   #:screen-drain-queue
   #:reset-sgr-pen))
