(in-package #:nerimux/terminal/parser)

(define-state ground-state (screen byte)
  (#x1B  #'escape-state)
  (#x0D  (cursor-cr screen) #'ground-state)
  (#x0A  (cursor-nl screen) #'ground-state)
  (#x0B  (cursor-nl screen) #'ground-state)
  (#x0C  (cursor-nl screen) #'ground-state)
  (#x08  (cursor-bs screen) #'ground-state)
  (#x09  (cursor-ht screen) #'ground-state)
  (#x07  (set-bell-pending screen)
         (screen-record-notification screen (vector #x07) "")
         #'ground-state)
  (#x7F  #'ground-state)
  (#x0E  (invoke-charset screen :g1) #'ground-state)
  (#x0F  (invoke-charset screen :g0) #'ground-state)
  (printable-ascii-p
   (write-char-at-cursor screen (code-char byte))
   #'ground-state)
  (utf8-lead-p
   (multiple-value-bind (code-point-accumulator continuation-bytes-remaining)
       (utf8-lead-decode byte)
     (make-utf8-k code-point-accumulator continuation-bytes-remaining)))
  ((>= byte #x80)
   (write-codepoint screen #xFFFD)
   #'ground-state)
  (t #'ground-state))

(define-state escape-state (screen byte)
  (#x5B  (make-csi-k '() nil nil))
  (#x5D  #'osc-state)
  (#x50  (make-dcs-k))
  (#x4D  (cursor-ri screen)    #'ground-state)
  (#x63  (ris-action screen)   #'ground-state)
  (#x37  (save-cursor screen)    #'ground-state)
  (#x38  (restore-cursor screen) #'ground-state)
  (#x44  (cursor-lf  screen)     #'ground-state)
  (#x45  (cursor-nel screen)     #'ground-state)
  (#x48  (set-tab-stop screen)   #'ground-state)
  (#x28  (make-charset-designator-k :g0))
  (#x29  (make-charset-designator-k :g1))
  (#x2A  (make-charset-designator-k :g2))
  (#x2B  (make-charset-designator-k :g3))
  (#x6E  (invoke-charset screen :g2) #'ground-state)
  (#x6F  (invoke-charset screen :g3) #'ground-state)
  (#x4E  (setf (screen-single-shift screen) :g2) #'ground-state)
  (#x4F  (setf (screen-single-shift screen) :g3) #'ground-state)
  (#x20  (make-ignore-final-byte-k))
  (#x25  (make-ignore-final-byte-k))
  (#x23  (make-hash-line-size-k))
  (t     #'ground-state))

(define-state osc-state (screen byte)
  (#x07  #'ground-state)
  (#x1B  #'osc-st-state)
  (t     (let ((payload-buffer (make-array 64
                                           :element-type '(unsigned-byte 8)
                                           :fill-pointer 0
                                           :adjustable t))
                 (raw-buffer (make-array 64
                                         :element-type '(unsigned-byte 8)
                                         :fill-pointer 0
                                         :adjustable t)))
           (vector-push-extend byte payload-buffer)
           (vector-push-extend #x1B raw-buffer)
           (vector-push-extend #x5D raw-buffer)
           (vector-push-extend byte raw-buffer)
           (make-osc-k payload-buffer raw-buffer))))

(define-state osc-st-state (screen byte)
  (#x5C  #'ground-state)
  (t     #'osc-state))
