(in-package #:nerimux/terminal/types)

(defstruct (screen (:constructor %make-screen))
  "Virtual terminal screen: cursor, cell grid, and CPS parser continuation."
  (width    +default-screen-width+  :type fixnum)
  (height   +default-screen-height+ :type fixnum)
  (cells    #() :type simple-vector)
  (cursor-x 0 :type fixnum)
  (cursor-y 0 :type fixnum)
  (cur-fg    +default-color+ :type (unsigned-byte 25))
  (cur-bg    +default-color+ :type (unsigned-byte 25))
  (cur-attrs 0 :type (unsigned-byte 8))
  (cursor-visible t :type boolean)
  (scroll-top    0                             :type fixnum)
  (scroll-bottom (1- +default-screen-height+) :type fixnum)
  (parser #'identity :type function)
  (dirty-p t :type boolean)
  (lock nil :type (or null cl-concurrent-kit:lock))
  (alt-cells nil)                           ; saved normal-screen cell grid, or nil
  (alt-cursor-x 0 :type fixnum)            ; cursor column saved on alt-screen entry
  (alt-cursor-y 0 :type fixnum)            ; cursor row saved on alt-screen entry
  (saved-cursor nil :type list)
  (copy-mode-p  nil  :type boolean)
  (copy-hide-position nil :type boolean)
  (copy-offset  0    :type fixnum)          ; lines scrolled back (0 = live view)
  (scrollback   nil  :type list)            ; list of row-vectors, newest first
  (scrollback-wrapped nil :type list)
  (prompt-marks nil :type list)
  (history-trimmed 0 :type integer)
  (line-sizes (make-hash-table) :type hash-table)
  (copy-mark    nil  :type list)            ; (row . col) mark position, NIL = no selection
  (copy-mark-offset 0 :type fixnum)         ; copy-offset in effect when copy-mark was set
  (copy-cursor  nil  :type list)
  (copy-selecting nil :type boolean)        ; T when selection is being built
  (copy-exit-on-bottom nil :type boolean)
  (copy-mode-entered-by-mouse-p nil :type boolean)
  (last-char nil :type (or null character))
  (cursor-shape 1 :type (unsigned-byte 8))
  (insert-mode nil :type boolean)
  (newline-mode nil :type boolean)
  (reverse-screen nil :type boolean)
  (bracketed-paste nil :type boolean)
  (app-cursor-keys nil :type boolean)
  (title "" :type string)
  (title-stack nil :type list)
  (cwd "" :type string)
  (autowrap t :type boolean)
  (pending-wrap nil :type boolean)
  (origin-mode nil :type boolean)
  (focus-events nil :type boolean)
  (charset :ascii :type (member :ascii :dec-graphics))
  (g0-charset :ascii :type (member :ascii :dec-graphics))
  (g1-charset :ascii :type (member :ascii :dec-graphics))
  (g2-charset :ascii :type (member :ascii :dec-graphics))
  (g3-charset :ascii :type (member :ascii :dec-graphics))
  (active-g :g0 :type (member :g0 :g1 :g2 :g3))
  (single-shift nil :type (member nil :g2 :g3))
  (tab-stops :default)
  (cur-ul-color 0 :type (unsigned-byte 25))
  (cur-attrs2 0 :type (unsigned-byte 8))
  (response-queue nil :type list)
  (passthrough-queue nil :type list)
  (clipboard-queue nil :type list)
  (bell-pending nil :type boolean)
  (copy-search-term nil :type (or null string))
  (copy-search-direction nil :type (or null keyword))
  (copy-search-index nil :type (or null fixnum))
  (copy-search-total 0 :type fixnum)
  (copy-line-selection-p nil :type boolean)
  (copy-rect-select-p nil :type boolean)
  (osc-default-fg +osc-default-fg+ :type (unsigned-byte 24))
  (osc-default-bg +osc-default-bg+ :type (unsigned-byte 24))
  (current-hyperlink nil :type (or null string))
  (palette-overrides nil :type (or null simple-vector))
  (wrapped-rows nil :type (or null hash-table)))
