(in-package #:nerimux/test)

;;;; define-message-dispatch-fn macro engine and runtime registry tests

;;; %handle-client-message (the single-client wrapper, define-msg-dispatch) and
;;; the CPS keystroke walker it dispatched into were deleted with the
;;; single-client server path.  define-message-dispatch-fn itself is still
;;; live: define-multi-msg-dispatch (server-multi-dispatch.lisp) builds
;;; %handle-multi-client-message from it.  This expands the macro into a
;;; throwaway dispatch function of its own so the shared COND-expansion engine
;;; stays under direct test without duplicating the multi-client forwarding
;;; coverage owned elsewhere.
(nerimux::define-message-dispatch-fn
    nerimux::%test-only-message-dispatch-fn (msg-type payload)
    "Test-only dispatch function generated by define-message-dispatch-fn."
  ((null msg-type) :nil-arm)
  ((eq msg-type :known) (list :known-arm payload))
  (t :fallback-arm))

(describe "server-suite"

  ;;; -- run-server session-registry initialization ------------------------------

  ;; The session-registry setup that run-server performs: reset to NIL then add the initial session.
  (it "run-server-session-registry-initialization"
    (unless (pty-available-p) (skip "no PTY available (sandboxed environment)"))
    (with-empty-registry
      (let ((nerimux/model::*session-id-counter* 0))
        (setf nerimux::*server-sessions* nil)
        (let ((session (create-initial-session 24 80)))
          (nerimux::server-add-session session)
          (expect (= 1 (length nerimux::*server-sessions*)))
          (expect (nerimux::server-find-session (session-name session)) :to-be-truthy)
          (dolist (pane (all-panes session))
            (ignore-errors (pty-close (pane-fd pane) (pane-pid pane))))))))

  ;;; -- define-message-dispatch-fn macro ---------------------------------------
  ;;;
  ;;; Exercises nerimux::%test-only-message-dispatch-fn, generated above by
  ;;; define-message-dispatch-fn -- the shared COND-expansion engine that also
  ;;; builds %handle-multi-client-message (still live and in use).

  ;; define-message-dispatch-fn must produce a DEFUN whose symbol is fbound.
  (it "define-message-dispatch-fn-generated-function-is-fbound"
    (expect (fboundp 'nerimux::%test-only-message-dispatch-fn)))

  ;; The generated function must send each COND arm to its own body, in
  ;; declaration order -- not always the first arm, and not always the last.
  (it "define-message-dispatch-fn-returns-same-as-cond-table"
    (expect (eq :nil-arm (nerimux::%test-only-message-dispatch-fn nil :ignored)))
    (expect (equal '(:known-arm :payload-value)
                    (nerimux::%test-only-message-dispatch-fn :known :payload-value)))
    (expect (eq :fallback-arm
                (nerimux::%test-only-message-dispatch-fn :unrecognised nil))))

  ;; The two apply-client-size tests that used to close this block were removed
  ;; with the function: it had no production caller left (the multi-client path
  ;; resizes through %apply-effective-size in server-multi.lisp), so these tests
  ;; were the only thing keeping it alive.
  )
