(in-package #:nerimux/test)

(describe "server-multi-command-suite"

  (it "multi-client-ui-command-state-is-private"
    (with-fake-session (s)
      (let ((conn (%make-test-conn)))
        (expect (nerimux::%client-ui-keys-p conn))
        (expect (nerimux::%handle-client-ui-command s conn :mode nil '("copy")))
        (expect (eq :scrollback (nerimux::client-conn-modal conn)))
        (expect (nerimux::%handle-client-ui-command s conn :viewport nil '("3")))
        (expect (= 3 (nerimux::client-conn-viewport conn)))
        (expect (nerimux::%handle-client-ui-command s conn :viewport nil '("-1")))
        (expect (= 2 (nerimux::client-conn-viewport conn)))
        (expect (null (nerimux::%handle-client-ui-command s conn :mode nil '("not-a-mode"))))
        (expect (eq :scrollback (nerimux::client-conn-modal conn)))
        (expect (nerimux::%handle-client-ui-command s conn :focus nil '("not-a-pane")))
        (expect (nerimux::%handle-client-ui-command s conn :focus nil nil))
        (expect (eq (nerimux::window-active-pane (nerimux::session-active-window s))
                    (nerimux::client-conn-focus conn)))
        (expect (nerimux::%handle-client-ui-command s conn :viewport nil '("bad")))
        (expect (= 0 (nerimux::client-conn-viewport conn)))
        (expect (nerimux::%handle-client-ui-command s conn :cancel nil nil))
        (expect (null (nerimux::client-conn-modal conn)))
        (expect (nerimux::%handle-client-ui-command s conn :enter-copy nil nil))
        (expect (eq :scrollback (nerimux::client-conn-modal conn)))
        (expect (nerimux::%handle-client-ui-command s conn :toggle-copy nil nil))
        (expect (null (nerimux::client-conn-modal conn)))
        (expect (nerimux::%handle-client-ui-command s conn :enter-input nil nil))
        (expect (eq :pane (nerimux::client-conn-view conn)))
        (expect (nerimux::%handle-client-ui-command s conn :enter-normal nil nil))
        (expect (null (nerimux::client-conn-modal conn)))
        (expect (nerimux::%handle-client-ui-command s conn :detail nil nil))
        (expect (eq :pane (nerimux::client-conn-view conn)))
        (expect (nerimux::%handle-client-ui-command s conn :home nil nil))
        (expect (eq :repolist (nerimux::client-conn-view conn)))
        (expect (nerimux::%handle-client-ui-command s conn :tree-scroll nil '("bad")))
        (expect (= 0 (nerimux::client-conn-tree-scroll conn))))))

  (it "ui-command-mode-and-picker-transitions-share-a-small-contract"
    (with-fake-session (s)
      (let ((conn (%make-test-conn)) (calls nil))
        (with-stubbed-fdefinition
            ((nerimux::%open-client-picker (lambda (conn) (push :open calls) (setf (nerimux::client-conn-modal conn) :picker)))
             (nerimux::%close-client-picker (lambda (conn) (push :close calls) (setf (nerimux::client-conn-modal conn) nil)))
             (nerimux::%select-client-picker-item (lambda (session conn) (declare (ignore session)) (push :select calls) (setf (nerimux::client-conn-modal conn) nil) t))
             (nerimux::%client-enter-copy-mode (lambda (session conn) (declare (ignore session)) (setf (nerimux::client-conn-modal conn) :scrollback))))
          (expect (nerimux::%handle-client-ui-command s conn :mode nil '("picker")))
          (expect (eq :picker (nerimux::client-conn-modal conn)))
          (expect (nerimux::%handle-client-ui-command s conn :picker-close nil nil))
          (expect (null (nerimux::client-conn-modal conn)))
          (expect (nerimux::%handle-client-ui-command s conn :mode nil '("picker")))
          (expect (nerimux::%handle-client-ui-command s conn :cancel nil nil))
          (expect (null (nerimux::client-conn-modal conn)))
          (expect (nerimux::%handle-client-ui-command s conn :mode nil '("picker")))
          (expect (nerimux::%handle-client-ui-command s conn :accept nil nil))
          (expect (null (nerimux::client-conn-modal conn)))
          (expect (nerimux::%handle-client-ui-command s conn :mode nil '("copy")))
          (expect (eq :scrollback (nerimux::client-conn-modal conn)))
          (dolist (mode '(:normal :input :command :tree-filter)) (expect (nerimux::%handle-client-ui-command s conn mode nil nil)))
          (expect (nerimux::%handle-client-ui-command s conn :copy nil nil))
          (expect (eq :scrollback (nerimux::client-conn-modal conn)))
          (expect (nerimux::%handle-client-ui-command s conn :cancel nil nil))
          (expect (null (nerimux::client-conn-modal conn)))
          (expect (equal '(:select :open :close :open :close :open) calls))))))

  (it "ui-command-aliases-preserve-command-contract"
    (with-fake-session (s)
      (let ((conn (%make-test-conn)) (calls nil))
        (with-stubbed-fdefinition
            ((nerimux::%client-rebind-prefix (lambda (conn prefix) (declare (ignore conn)) (push (list :prefix prefix) calls)))
             (nerimux::%select-client-tree-relative (lambda (conn delta) (declare (ignore conn)) (push (list :tree delta) calls)))
             (nerimux::%move-client-tree-scroll (lambda (conn delta) (declare (ignore conn)) (push (list :scroll delta) calls))))
          (expect (nerimux::%handle-client-ui-command s conn :prefix-key "C-x" nil))
          (expect (nerimux::%handle-client-ui-command s conn :tree-prev nil '("2")))
          (expect (nerimux::%handle-client-ui-command s conn :tree-next nil nil))
          (expect (nerimux::%handle-client-ui-command s conn :tree-scroll nil '("bad")))
          (expect (equal '((:scroll 1) (:tree 1) (:tree -2) (:prefix "C-x")) calls))))))

  (it "picker-command-actions-share-a-small-dispatch-contract"
    (with-fake-session (s)
      (let ((conn (%make-test-conn)) (calls nil))
        (with-stubbed-fdefinition
            ((nerimux::%select-client-picker-item (lambda (session conn) (declare (ignore session conn)) (push :select calls)))
             (nerimux::%refresh-client-picker (lambda (conn) (declare (ignore conn)) (push :refresh calls)))
             (nerimux::%mark-dirty (lambda () (push :dirty calls)))
             (nerimux::%move-client-picker-index (lambda (conn delta) (declare (ignore conn)) (push (list :move delta) calls)))
             (nerimux::%delete-client-picker-query-character (lambda (conn) (declare (ignore conn)) (push :backspace calls)))
             (nerimux::%set-client-picker-query (lambda (conn value) (declare (ignore conn)) (push (list :query value) calls)))
             (nerimux::%set-client-picker-regex (lambda (conn value supplied-p) (declare (ignore conn)) (push (list :regex value supplied-p) calls))))
          (dolist (command '((:picker-accept nil nil) (:picker-refresh nil nil) (:picker-next "2" nil) (:picker-up "2" nil) (:picker-backspace nil nil) (:picker-query "needle" nil) (:picker-query nil ("from-args")) (:picker-regex "pattern" nil) (:picker-regex nil ("from-args"))))
            (destructuring-bind (name target args) command (expect (nerimux::%handle-client-ui-command s conn name target args))))
          (expect (equal '((:regex "from-args" ("from-args")) (:regex "pattern" "pattern") (:query "from-args") (:query "needle") :backspace (:move -2) (:move 2) :dirty :refresh :select) calls)))))))
