(in-package #:nerimux/test)

;;;; define-message-dispatch-fn macro engine and runtime registry tests

;;; %handle-client-message (the single-client wrapper, define-msg-dispatch) and
;;; the CPS keystroke walker it dispatched into were deleted with the
;;; single-client server path.  define-message-dispatch-fn itself is still
;;; live: define-multi-msg-dispatch (server.lisp) builds
;;; %handle-multi-client-message from it.  This expands the macro into a
;;; throwaway dispatch function of its own so the shared COND-expansion engine
;;; stays under direct test without duplicating the multi-client forwarding
;;; coverage owned elsewhere.
(nerimux::define-message-dispatch-fn
    nerimux::%test-only-message-dispatch-fn (msg-type payload)
    "Test-only dispatch function generated by define-message-dispatch-fn."
  ((null msg-type) :nil-arm)
  ((eq msg-type :known) (list :known-arm payload))
  (t :fallback-arm))

(describe "server-suite"

  ;;; -- define-message-dispatch-fn macro ---------------------------------------
  ;;;
  ;;; run-server-session-registry-initialization (the session-registry setup
  ;;; that run-server performs, spawning a real PTY-backed session via
  ;;; create-initial-session) moved to tests/pty/server-client-cps-pty-tests.lisp
  ;;; (R9.2).  The two macro-engine cases below spawn nothing.
  ;;;
  ;;; Exercises nerimux::%test-only-message-dispatch-fn, generated above by
  ;;; define-message-dispatch-fn -- the shared COND-expansion engine that also
  ;;; builds %handle-multi-client-message (still live and in use).

  ;; define-message-dispatch-fn must produce a DEFUN whose symbol is fbound.
  (it "define-message-dispatch-fn-generated-function-is-fbound"
    (expect (fboundp 'nerimux::%test-only-message-dispatch-fn)))

  ;; The generated function must send each COND arm to its own body, in
  ;; declaration order -- not always the first arm, and not always the last.
  (it "define-message-dispatch-fn-returns-same-as-cond-table"
    (expect (eq :nil-arm (nerimux::%test-only-message-dispatch-fn nil :ignored)))
    (expect (equal '(:known-arm :payload-value)
                    (nerimux::%test-only-message-dispatch-fn :known :payload-value)))
    (expect (eq :fallback-arm
                (nerimux::%test-only-message-dispatch-fn :unrecognised nil))))

  (it "session-pane-lifecycle-functions-visit-every-pane"
    (let ((events nil))
      (with-stubbed-fdefinition
          ((nerimux::all-panes
            (lambda (session) (declare (ignore session)) '(:pane-a :pane-b)))
           (nerimux::start-reader-thread
            (lambda (pane) (push (list :start-reader pane) events)))
           (nerimux::close-pane-pty
            (lambda (pane) (push (list :close-pty pane) events))))
        (nerimux::%start-session-reader-threads :session)
        (nerimux::%close-session-ptys :session)
        (expect (equal '((:close-pty :pane-b)
                         (:close-pty :pane-a)
                         (:start-reader :pane-b)
                         (:start-reader :pane-a))
                       events)))))

  (it "relayout-active-window-is-a-noop-without-an-active-window"
    (let ((calls nil))
      (with-stubbed-fdefinition
          ((nerimux::session-active-window (lambda (session)
                                             (declare (ignore session))
                                             nil))
           (nerimux::window-relayout (lambda (&rest args)
                                       (push args calls))))
        (expect (null (nerimux::%relayout-active-window :session 24 80)))
        (expect (null calls)))))

  (it "relayout-active-window-reserves-the-status-row"
    (let ((calls nil))
      (with-stubbed-fdefinition
          ((nerimux::session-active-window (lambda (session)
                                             (declare (ignore session))
                                             :window))
           (nerimux::window-relayout (lambda (&rest args)
                                       (push args calls))))
        (nerimux::%relayout-active-window :session 24 80)
        (expect (equal '(:window 23 80) (first calls))))))

  (it "run-server-initializes-and-cleans-up-around-loop"
    (let ((events nil)
          (stop-tag (gensym "SERVER-STOP")))
      (with-stubbed-fdefinition
          ((nerimux::install-pty-port
            (lambda () (push :install-pty-port events)))
           (nerimux::create-initial-session
            (lambda (rows cols)
              (push (list :create-session rows cols) events)
              :session))
           (nerimux::socket-path
            (lambda (name) (push (list :socket-path name) events) "/tmp/nerimux-test.sock"))
           (nerimux::server-add-session
            (lambda (session) (push (list :add-session session) events)))
           (nerimux/net::make-listener
            (lambda (path &key backlog)
              (push (list :make-listener path backlog) events)
              :listener))
           (nerimux::all-panes
            (lambda (session) (declare (ignore session)) '(:pane-a)))
           (nerimux::start-reader-thread
            (lambda (pane)
              (declare (ignore pane))
              :reader-thread))
           (nerimux::stop-reader-threads
            (lambda (threads)
              (push (list :stop-reader-threads threads) events)))
           (nerimux::install-sigwinch-handler
            (lambda () (push :install-sigwinch-handler events)))
           (nerimux::%run-multi-server-loop
            (lambda (listener session)
              (push (list :run-loop listener session) events)
              (throw stop-tag :loop-ended)))
           (nerimux/net::close-socket
            (lambda (listener &key abort)
              (push (list :close-socket listener abort) events)))
           (nerimux::close-pane-pty
            (lambda (pane) (declare (ignore pane)) (push :close-pane events))))
        (expect (eq :loop-ended
                    (catch stop-tag (nerimux::run-server "demo"))))
        (expect (equal :install-pty-port (first (last events))))
        (expect (member '(:run-loop :listener :session) events :test #'equal))
        (expect (member '(:stop-reader-threads (:reader-thread))
                        events :test #'equal))
        (expect (member '(:close-socket :listener nil) events :test #'equal)))))

  ;; The two apply-client-size tests that used to close this block were removed
  ;; with the function: it had no production caller left (the multi-client path
  ;; resizes through %apply-effective-size in server-multi.lisp), so these tests
  ;; were the only thing keeping it alive.
  )
