(in-package #:nerimux)

(defparameter *dispatch-command-specs-core-session-entries*
  '((:new-window '%cmd-new-window-arg ("new-window"))
    (:new-session '%cmd-new-session-arg ("new-session"))
    (:kill-session '%cmd-kill-session-arg ("kill-session"))
    (:detach '%cmd-detach-arg ("detach" "detach-client"))
    (:next-window '%cmd-next-window-arg ("next-window"))
    (:prev-window '%cmd-previous-window-arg ("previous-window"))
    (:rename-session '%cmd-rename-session ("rename-session"))
    (:list-sessions '%cmd-list-sessions-arg ("list-sessions"))
    (:choose-session nil ("choose-session"))
    (:refresh-client '%cmd-refresh-client-arg ("refresh-client"))
    (:choose-client '%cmd-choose-client ("choose-client"))
    (:lock-session '%cmd-lock-session-arg ("lock-session"))
    (:unlock-session nil ("unlock-session"))
    (:has-session '%cmd-has-session-arg ("has-session"))
    (:wait-for '%cmd-wait-for-arg ("wait-for"))
    (:server-info nil ("server-info"))
    (:list-clients '%cmd-list-clients-arg ("list-clients"))
    (:suspend-client nil ("suspend-client"))
    (:lock-server nil ("lock-server"))
    (:kill-server '%cmd-kill-server ("kill-server"))
    (:start-server nil ("start-server"))
    (:attach-session '%cmd-attach-session-arg ("attach-session"))
    (:show-environment '%cmd-show-environment-arg ("show-environment"))
    (:set-environment '%cmd-set-environment-prompt ("set-environment"))
    (:show-prompt-history nil ("show-prompt-history"))
    (:clear-prompt-history nil ("clear-prompt-history"))
    (:detach-all-clients nil ("detach-all-clients"))
    (:switch-client '%cmd-switch-client ("switch-client"))
    (:lock-client '%cmd-lock-client-arg ("lock-client"))
    (:display-info nil ("display-info"))))
