(in-package #:nerimux)

(define-key-rules %handle-client-ui-key-payload
                  (session conn payload)
                  (:let ((view (client-conn-view conn))))
                  ((gethash conn *client-meta-pending*)
                   (%client-meta-pending-consume conn payload))
                  (27
                   (setf (gethash conn *client-meta-pending*) :second)
                   t)
                  (#\n (%select-client-tree-relative conn 1) t)
                  (#\p (%select-client-tree-relative conn -1) t)
                  (9 (%client-toggle-selected-tree-row conn))
                  (#\1 (%client-set-visibility-level conn 1))
                  (#\2 (%client-set-visibility-level conn 2))
                  (#\3 (%client-set-visibility-level conn 3))
                  (#\4 (%client-set-visibility-level conn 4))
                  ((or (%client-byte-p payload 13) (%client-byte-p payload 10))
                   (%focus-selected-client-worktree session conn))
                  (#\g (%client-refresh-workspace conn))
                  (#\q (%client-step-back session conn))
                  ((and (eq view :repolist) (%client-key-p payload #\t))
                   (%client-open-selected-worktree-command session conn nil))
                  ((and (eq view :repolist) (%client-key-p payload #\c))
                   (%client-open-selected-worktree-command session
                                                           conn
                                                           +workspace-claude-command+))
                  ((and (eq view :repolist) (%client-key-p payload #\x))
                   (%client-open-selected-worktree-command session
                                                           conn
                                                           +workspace-codex-command+))
                  (#\$ (%set-client-modal conn :process-log) t)
                  (#\/ (%client-enter-tree-filter-mode conn))
                  (#\: (%client-enter-command-mode conn))
                  (#\? (%open-client-transient conn #\?))
                  ((and (eq view :status) (%client-key-p payload #\s))
                   (%client-stage-selection conn))
                  ((and (eq view :status) (%client-key-p payload #\S))
                   (%client-stage-all conn))
                  ((and (eq view :status) (%client-key-p payload #\u))
                   (%client-unstage-selection conn))
                  ((and (eq view :status) (%client-key-p payload #\U))
                   (%client-unstage-all conn))
                  ((and (eq view :status) (%client-key-p payload #\k))
                   (%client-start-discard-selection conn))
                  ((and (eq view :status) (%client-key-p payload #\c))
                   (%open-client-transient conn #\c))
                  ((and (eq view :status) (%client-key-p payload #\P))
                   (%open-client-transient conn #\P))
                  ((and (eq view :status) (%client-key-p payload #\F))
                   (%open-client-transient conn #\F))
                  ((and (eq view :status) (%client-key-p payload #\b))
                   (%open-client-transient conn #\b))
                  ((and (eq view :status) (%client-key-p payload #\m))
                   (%open-client-transient conn #\m))
                  ((and (eq view :status) (%client-key-p payload #\r))
                   (%open-client-transient conn #\r))
                  ((and (eq view :status) (%client-key-p payload #\z))
                   (%open-client-transient conn #\z))
                  ((and (eq view :status) (%client-key-p payload #\l))
                   (%open-client-transient conn #\l))
                  ((and (eq view :status) (%client-key-p payload #\d))
                   (%open-client-transient conn #\d))
                  ((and (eq view :status) (%client-key-p payload #\f))
                   (%open-client-transient conn #\f))
                  ((and (eq view :status) (%client-key-p payload #\t))
                   (%open-client-transient conn #\t))
                  ((and (eq view :status) (%client-key-p payload #\X))
                   (%open-client-transient conn #\X))
                  ((and (eq view :status) (%client-key-p payload #\!))
                   (%open-client-transient conn #\!))
                  ((and (eq view :status) (%client-key-p payload #\w))
                   (%open-client-transient conn #\w))
                  (t nil))
